### ISSUE TITLE
Club Event TDD 기반 작성

### ISSUE THREAD

**Issue by hyunbin1** [GBFStudio/NawaBack#36]
## TODO
- [ ] 1. 앨범 목록 페이지네이션 조회
- [ ] 2. 앨범 상세 조회
- [ ] 3. 앨범 좋아요 추가
- [ ] 4. 앨범 좋아요 취소
- [ ] 5. 앨밤 댓글 목록 페이지네이션 조회
- [ ] 6. 앨범 댓글 좋아요 추가
- [ ] 7. 앨범 댓글 좋아요 취소
